version: '2'

services:
  login:
    build: .
    command: npm run dev
    environment:
      - LOGSTASH_SERVICE_HOST=logstash
      - LOGSTASH_SERVICE_PORT=5000
    links:
      - auth
      - user
      - logstash
      - rethinkdb
    ports:
      - "8080:8080"
    volumes:
      - ./service/src:/service/src
  auth:
    image: hharnisc/auth
    command: npm start
    environment:
      - LOGSTASH_SERVICE_HOST=logstash
      - LOGSTASH_SERVICE_PORT=5000
      - JWT_SECRET=secret
    links:
      - rethinkdb
      - logstash
    expose:
      - "8080"
  user:
    image: hharnisc/user
    command: npm start
    environment:
      - LOGSTASH_SERVICE_HOST=logstash
      - LOGSTASH_SERVICE_PORT=5000
    links:
      - rethinkdb
      - logstash
    expose:
      - "8080"
  elasticsearch:
    image: hharnisc/elasticsearch:v1
    expose:
      - "9200"
  logstash:
    image: hharnisc/logstash:v2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    expose:
      - "5000"
    links:
      - elasticsearch
  kibana:
    image: hharnisc/kibana:v1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  rethinkdb:
    image: rethinkdb
    expose:
      - "28015"
    ports:
      - "8081:8080"
